### ISSUE TITLE
Version bumper errors and doesn't bump the version on a feature branch when using the pull-request trigger

### ISSUE THREAD

**Issue by MarkIannucci** [michmich112/version-bumper#35]
I configured my github actions [workflow file](https://github.com/MarkIannucci/ChromeUserWebSearchExtension/blob/e4217d6072f6ceb5a9b15bf1d7f0ff2a85f5b11f/.github/workflows/build.yml#L5-L9) with the following settings:
```yaml
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
````
I noticed when the action runs [with the rules](https://github.com/MarkIannucci/ChromeUserWebSearchExtension/blob/a5c28e719d0da637b301070fbdcaf80917e84429/.github/version-bumper-options.json#L6-L10) configured to bump the version on `pull-request`, I get the following error in the action:

````
/usr/bin/git checkout PushToChromeStore
error: pathspec 'PushToChromeStore' did not match any file(s) known to git
Error: The process '/usr/bin/git' failed with exit code 1
````

I'm not sure why it is having problems checking out the branch.
